[package]
name = "remote_socket_integration"
version = "0.1.0"
authors = ["Jonas Greifenhain <jonas@greifenhain.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
